config/routes.rb
HnClone::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :users

  root to: 'links#index'

  resources :links do
    resources :comments
  end

  resources :sessions

  resources :votes

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :link
  belongs_to :commentable, :polymorphic => true
  has_many :comments, :as =>  :commentable

  attr_accessible :body, :link_id

end

app/models/link.rb
class Link < ActiveRecord::Base

  attr_accessible :url, :created_at, :user_id, :vote_count
  belongs_to :user
  has_many :comments, :as => :commentable
  has_many :votes

  validates :url, uniqueness: true

  #delegate :count, :to => :votes, :prefix => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :id, :password_confirmation
  has_many :links
  has_many :comments
  has_many :votes, :through => :links


  before_save { |user| user.email = email.downcase }

  validates_confirmation_of :password
  validates :email, presence: true, length: {maximum: 50}, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password == password
      user
    else
      nil
    end #end if
  end #end authenticate

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :vote_status, :user_id, :link_id

  belongs_to :link
  belongs_to :user

  after_create :update_link_vote_count

  def update_link_vote_count
    link.vote_count ||= 0
    link.vote_count += 1
    link.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end


  def new
    @comment = Comment.new

  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.user_id = current_user.id
    @comment.commentable_id = params[:link_id]
    @comment.commentable_type = "Link"
    @comment.save

    redirect_to link_path(@comment.commentable_id)

  end

  def show



  end

  def edit
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.json
  def index

    @links = Link.order('vote_count DESC')


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
    @comment = Comment.new
    @comments = Comment.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = current_user.links.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])
    if session[:user_id]
      @link.user_id = User.find(session[:user_id]).id
    end

    respond_to do |format|
      if @link.save
        format.html { redirect_to links_path, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = current_user.links.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = current_user.links.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to links_path, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end #end if
  end #end create

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, :notice => "Logged out!"
  end

  def show

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  # def index
  #   @users = User.all
  # 
  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @users }
  #   end
  # end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


  def new

  @vote = Vote.new

  end

  def edit
  end

  def create
    @vote = Vote.new(params[:vote])
    @vote.user = current_user
    @vote.save

    redirect_to links_path
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/links_helper.rb
module LinksHelper

  def can_vote?(link)
    if current_user.nil? || link.user == current_user || link.votes.find_by_user_id(current_user.id)
      false
    else
      true
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  #Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end

end

app/helpers/votes_helper.rb
module VotesHelper



end

app/views/comments/_comments.html.erb
<%= form_for [@link, @comment] do |f| %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<table>
  <tr>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @link.comments.each do |comment| %>
  <tr>

    <td><%= comment.body %></td>

  </tr>
<% end %>
</table>

app/views/comments/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comment#edit</h1>
<p>Find me in app/views/comment/edit.html.erb</p>

app/views/comments/index.html.erb
<table>
  <tr>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>

    <td><%= comment.body %></td>

  </tr>
<% end %>
</table>

app/views/comments/new.html.erb
<h1>Comment#new</h1>

<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/show.html.erb
<h1>Comment#show</h1>
<p>Find me in app/views/comment/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HnClone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="container">
      <div id="user_nav">
        <p class="nav pull-left" >

          <% if current_user %>
            Logged in as <%= current_user.email %>
            <%= link_to "Log out", log_out_path %>
          <% else %>
            <%= link_to "Sign up", new_user_path %> or
            <%= link_to "Log in", new_session_path %>
          <% end %>
        </p>
      </div>
    </div>
</header>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
 <% end %>
<%= yield %>
<br><br>
<%= link_to "Submit New Link", new_link_path %>


</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h> Faux Hacker News</h1>

<table>
  <tr>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <% if can_vote?(link) %>
    <td><%= button_to "Vote", votes_path(:vote => {:link_id => link.id, :vote_status => true}) %></td>
    <% else %>
    <td></td>
    <% end %>
    <td><%= link_to link.url, link.url %></td>
    <td><%= link_to 'Comment', link %></td>

  </tr>
<% end %>
</table>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Link:</b>
  <%= link_to "#{@link.url}", @link.url %>
</p>


<%= link_to 'Back', links_path %>
<% if @link.user == current_user && (Time.now - @link.created_at)/60 < 15 %>
  <%= link_to "Edit", edit_link_path(@link) %>
  <% end %>


<%= render :partial =>"comments/comments" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_sign_in_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>User Sign In</h1>

<%= render 'sign_in_form' %>

<table>
  <tr>
    <th>Email</th>
    <br>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td><br>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>

<h1><%= gravatar_for @user %>
    <%= @user.email %>
  </h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>


<p>
  <b>My Links:</b><br />
  <% @user.links.each do |link| %>
<tr>
  <td><%= link_to link.url, link.url  %></td>&nbsp;&nbsp;
  <%= link_to 'Edit', edit_link_path(link) %><br />

</tr>

  <% end %>
</p>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/edit.html.erb
<h1>Votes#edit</h1>
<p>Find me in app/views/votes/edit.html.erb</p>

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>

app/views/votes/update.html.erb
<h1>Votes#update</h1>
<p>Find me in app/views/votes/update.html.erb</p>